Repository slub/slub_digitalcollections, pull requests merged in 2025-08, with the labels that each got.

#158 Add compatibility for Kitodo.Presentation Mediaplayer and TYPO3 v12
  Build/package-lock.json
  Classes/ViewHelpers/PageInfoViewHelper.php
  Configuration/TCA/Overrides/pages.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Resources/Private/Less/Controls.less
  Resources/Private/Less/Helper/Variables.less
  Resources/Private/Less/Sidebar.less
  Resources/Private/Less/Themes/Basictheme.less
  Resources/Private/Less/Themes/Slubtheme.less
  Resources/Private/Plugins/Kitodo/Partials/TableOfContents/Children.html
  Resources/Public/Css/BaseDesign.css
  Resources/Public/Css/Digitalcollections.css
  Resources/Public/Css/DigitalcollectionsLists.css
  Resources/Public/Images/Slub/viewerControlIcons.svg
  Resources/Public/Images/viewerControlIcons.svg
  Resources/Public/JavaScript/DigitalcollectionsListScripts.js
  Resources/Public/JavaScript/DigitalcollectionsScripts.js
  composer.json
  ext_localconf.php
Labels: enhancement

#159 Add multiViewType to `tx_dlf_pageview` in Kitodo config adapted from DFG-Viewer
  Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
Labels: maintenance

#160 [TASK] Add pageview container to empty workview
  Resources/Private/Partials/EmptyPageView.html
Labels: bug

#161 [BUGFIX] Set `multiViewType` to empty value
  Configuration/TypoScript/Plugin/Kitodo/setup.typoscript
Labels: bug

#157 Fix PageInfoViewHelper to retrieve page UID from routing context
  Classes/ViewHelpers/PageInfoViewHelper.php
Labels: bug
